// Auto-generated from src/config/colors.ts
// Do not edit this file directly - run 'npm run generate:colors' instead

import { Color } from 'three';

const WASHED_WHITE_VEC3_RGB = new Color('#FAF9F6').convertLinearToSRGB(); // washedWhite
const WOOD_BROWN_VEC3_RGB = new Color('#8B6C42').convertLinearToSRGB(); // woodBrown
const WOOD_BROWN_LIGHT_VEC3_RGB = new Color('#8B6C42').convertLinearToSRGB(); // woodBrown

export {
  WASHED_WHITE_VEC3_RGB,
  WOOD_BROWN_VEC3_RGB,
  WOOD_BROWN_LIGHT_VEC3_RGB,
};